### ISSUE TITLE
Question about evaluation server for the private test set

### ISSUE THREAD

**Issue by tedywond** [bdd100k/bdd100k#110]
I am currently working with BDD10K and would like to evaluate on the private test set. The link to the submission site says “We are moving our evaluation servers to Codalab. Stay tuned!”.  I was wondering about the timeline for the evaluation servers to be back up? Thanks!

**Comment by XiaLiPKU** [comment]
Which task do you evaluate on？

**Comment by tedywond** [comment]
the semantic segmentation task

**Comment by XiaLiPKU** [comment]
This is the link to it: https://competitions.codalab.org/competitions/31561
