### ISSUE TITLE
statistic the collection time of the segmented data set

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [bdd100k/bdd100k#120]
Why there are more than 3,000 pictures in 10k but not in 100k. How do I count the categories of 10k data, such as weather, timeofday. Because  my segment models trained on 10k are not good at night scenes, I want to count all the  picture information.

**Comment by XiaLiPKU** [comment]
That's a legacy problem for us. We aim to add these tags before the end of this year.

Still, thanks for your mentioning
