### ISSUE TITLE
Converting ins_seg to coco, formatting issues

### ISSUE THREAD

**Issue by pcicales** [bdd100k/bdd100k#126]
I am trying to convert the ins_seg annotations to coco format using the instructions provided at https://doc.bdd100k.com/format.html#format-conversion . As of now, I am not interested in the scalabel components as I am using a larger detection repo to run experiments with this data; I ran the following code with the correct directories on my end:

`python3 -m bdd100k.label.to_coco -m ins_seg|seg_track -i ${mask_base} -o ${out_path}`

where mask_base is where my training bitmasks are, in this case. The output was a json file with no annotations. What could cause this issue? I have checked the bitmasks and they are all there. Also, I ran the scalabel version:

`python3 -m bdd100k.label.to_coco -m ins_seg|seg_track -i ${in_path} -o ${out_path} -mb ${mask_base}`

which is giving me a complete json file in the RLE format. The issue I am having with this annotation set is that it appears to be causing issues in my other code (which I believe is due to the scalabel content). I am still looking into this but was wondering if there was any advice you could provide to me?

**Comment by XiaLiPKU** [comment]
> The issue I am having with this annotation set is that it appears to be causing issues in my other code (which I believe is due to the scalabel content)

Can you paste the error report here?

**Comment by XiaLiPKU** [comment]
More to say. If you want to generate coco with mask in polygon format instead of RLE, you can add `--mask-mode polygon` to the command line

**Comment by pcicales** [comment]
[Here is a link to the thread I am posting on regarding this isssue.](https://github.com/open-mmlab/mmdetection/issues/5261)

I am also running your solution now to see if it solves things.

**Comment by pcicales** [comment]
Hi @XiaLiPKU , going through the json files and comparing to [the coco formatting guidelines,](https://cocodataset.org/#format-data) I am having trouble understanding a few of the elements saved after running the `to_coco` script correctly. For example, it seems that type and video for example are not compatible with coco. Perhaps I am misunderstanding something, as I thought that these elements were retrieved using these keys (making it to where extra keys are not a problem). But I continue to have issues loading the data with pytorch assuming the data is formatted following the coco guidelines. Have you encountered this before?

**Comment by XiaLiPKU** [comment]
Indeed, we add some extra elements, and they are used for tracking problems (box_track & seg_track).
However, given my experience, these fields will not influence your usage of MMDet.

For the error reports, can you paste them here? Or you can upload the converted json files.

**Comment by pcicales** [comment]
Hello @XiaLiPKU sorry for the late reply, I wanted to make sure I wasnt making a mistake. The issue has nothing to do with how your json files are formatted (although there were some key differences that I had to change in order to match their requirements exactly, without deleting the extra entries). If anyone is interested, here is the thread [response](https://github.com/open-mmlab/mmdetection/issues/5261#issuecomment-857075816) where I outline my solution, and what is likely the cause of the problem. Thank you for your responsiveness and help!

**Comment by guifentian** [comment]
> More to say. If you want to generate coco with mask in polygon format instead of RLE, you can add `--mask-mode polygon` to the command line

@XiaLiPKU 
I am trying to convert to polygon format using `--mask-mode polygon` as you suggested. but it was not recognized.
>>error: unrecognized arguments: --mask-mode polygon

how to do that?
