### ISSUE TITLE
Regarding samples present in the train/val/test when comparing 100k, 10k, and seg_track_20

### ISSUE THREAD

**Issue by pcicales** [bdd100k/bdd100k#132]
Hello @XiaLiPKU  and @fyu.

I am planning on using the images that are not annotated for both the ins_seg and seg_track_20 tasks. If I were to annotate all of the train images present in the 100k train folder using a model trained using the 10k/seg_track_20 training set, would there be any images present there that are in the val/test sets of the ins_seg (10k) or seg_track_20 tasks? Or are the train/val/test splits all derived from the same videos, regardless of the task?

**Comment by thomasehuang** [comment]
There are some overlap between the 10K train set and the 100K/track val set, so you need to make sure to remove the overlapping ones.
