### ISSUE TITLE
to_coco fails when no corresponding label is found (using bdd100k - 10k images subset)

### ISSUE THREAD

**Issue by ArthDh** [bdd100k/bdd100k#152]
When I try to convert the 10k image subset the function
```
bdd100k2coco_det( )
```

leads to the error:
```
    if frame['labels']:
KeyError: 'labels'
```

when the following command is run:
```
python3 -m bdd100k.label.to_coco -m det -i "./labels/det_20/det_train.json" -o "./labels/det_20_coco/det_train.json"
```

An easy fix is to change the check 
```
    if frame['labels']:
```
to 
```
    if frame.get("labels", None):
```
Also, if the corresponding output directory is not found the ``` main() ```  function complains, we could just add:

```
    if not os.path.exists('/'.join(out_fn.split('/')[:-1])):
        os.mkdir('/'.join(out_fn.split('/')[:-1]))
``` 
before dumping output json to check for the output directory.

**Comment by XiaLiPKU** [comment]
Hi, ArthDh,

We don't have the function `bdd100k2coco_det( )` in the latest version of bdd100k.
Maybe you may pull the updating and run it again
