### ISSUE TITLE
How to report incorrect labels

### ISSUE THREAD

**Issue by erikreed** [bdd100k/bdd100k#155]
Hello, is there a preferred way to fix or report incorrect labels? They've been reported in previous issues [[1]](https://github.com/bdd100k/bdd100k/issues/20) [[2]](https://github.com/bdd100k/bdd100k/issues/51) and I've run into it as well. But not sure if there's an ideal process to report/fix these.

One example on `timeofday` in the 100k det_20 labels. Presumably this label is incorrect.

<details>

![Example image](https://user-images.githubusercontent.com/903366/126405171-2c65d40a-caaa-44b7-b254-90731d598cf1.png)

</details>

Image `bdd100k/images/100k/train/0de6128f-d367dc4d.jpg`, with a reported time-of-day of "night".
```
$ jq '.[] | select(.name == "0de6128f-d367dc4d.jpg") | .name,.attributes' bdd100k/labels/det_20/det_train.json 
"0de6128f-d367dc4d.jpg"
{
  "weather": "snowy",
  "timeofday": "night",
  "scene": "city street"
}
```

**Comment by thomasehuang** [comment]
Thanks for notifying us. We will release updated labels soon.
