### ISSUE TITLE
All lanes in lane masks or colormaps are solid

### ISSUE THREAD

**Issue by k-sokolov** [bdd100k/bdd100k#173]
Hello, I have been checking out the labels for lane line detection. It seems that all lanes are marked as solid ones (i.e. for every pixel value of a mask, its 3d bit is always 0). for example, check val/b1d0a191-de8948f6.jpg. I think there is no way to differentiate between the dashed and the solid lines on this image based by annotations.

**Comment by thomasehuang** [comment]
Thank you for notifying us of a mistake in the annotations.

We have double-checked the annotations according to your comment and found that indeed the bitmasks have issues. We have generated the train and val bitmasks and colormaps again and uploaded the new data to the download link at https://bdd-data.berkeley.edu/ . The issues should be fixed.

Let us know if you run into any further issues!
