### ISSUE TITLE
update bdd100k on pypi

### ISSUE THREAD

**Issue by JiweiMaster** [bdd100k/bdd100k#183]
can you update the bdd100k eval function on pypi?

**Comment by fyu** [comment]
OK. Meanwhile, you can add `git+git://github.com/bdd100k/bdd100k.git` to your requirements.txt for pip installation.

**Comment by JiweiMaster** [comment]
yes, but this methods cannot be used into 'python setup install'

**Comment by thomasehuang** [comment]
We will update it soon.
