### ISSUE TITLE
Could you provide the download link pre file? Or, could you provide a list of videos that are included in each video parts (18G)?

### ISSUE THREAD

**Issue by GuanxiongLiu** [bdd100k/bdd100k#184]

**Comment by fyu** [comment]
You can find lists of video names here: https://github.com/bdd100k/bdd100k/tree/master/bdd100k/data

**Comment by GuanxiongLiu** [comment]
Let me make the question clear. I have a list of videos that I need. Based on this link (https://doc.bdd100k.com/download.html#video-parts), the entire dataset is broken into 100 pieces. Therefore, I want to know the specific parts that contain the videos I need. Thanks

**Comment by fyu** [comment]
The videos were sorted before going to each part. You can also find the individual videos here http://dl.yf.io/bdd100k/
