### ISSUE TITLE
Assertion Error using to_coco.py

### ISSUE THREAD

**Issue by punyuenyi** [bdd100k/bdd100k#190]
I got this error every time when I run to_coco.py on google colab 

My code:
`!python3 -m bdd100k.label.to_coco -i /content/bdd100k_label/labels/train.json -o /content/det_v2_train_release_coco.json 
`
The error I got:

`[2021-11-07 12:46:50,950 to_coco.py:546 main] Start format converting...
  0% 0/69863 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/bdd100k/bdd100k/label/to_coco.py", line 557, in <module>
    main()
  File "/content/bdd100k/bdd100k/label/to_coco.py", line 547, in main
    frames = bdd100k_to_scalabel(dataset.frames, bdd100k_config)
  File "/content/bdd100k/bdd100k/label/to_scalabel.py", line 58, in bdd100k_to_scalabel
    image_anns.labels[i], bdd100k_config, cat_name2id
  File "/content/bdd100k/bdd100k/label/to_scalabel.py", line 35, in deal_bdd100k_category
    assert category_name in bdd100k_config.ignored_mapping
AssertionError
`
I have no idea how to solve this problem. Any help will be appreciated. Thanks!!

**Comment by tobiasfshr** [comment]
Could you give us more information on which data (bdd100k detection train?) you're trying to convert and which version of the code you're using (did you clone the latest master?). I can't reproduce your error locally when i convert the detection train set using the latest master branch.

**Comment by punyuenyi** [comment]
> Could you give us more information on which data (bdd100k detection train?) you're trying to convert and which version of the code you're using (did you clone the latest master?). I can't reproduce your error locally when i convert the detection train set using the latest master branch.


I'm converting the labels right next to 10k image downloaded from [https://bdd-data.berkeley.edu/portal.html#download](url)

using the latest version of master on google colab.

My code

`!git clone https://github.com/bdd100k/bdd100k`
`!pip install -r requirements.txt `
`!python3 setup.py install`
`!pip install -U nanoid numpy pydantic boto3`
`python3 -m bdd100k.label.to_coco -m det -i bdd100k_labels_images_val.json  -o val2.json `

Thank you so much!!!!

**Comment by tobiasfshr** [comment]
okay great that your issue is resolved.

**Comment by liuliaocheng** [comment]
> > 您能否向我们提供更多有关您尝试转换的数据（bdd100k 检测序列？）以及您使用的代码版本的更多信息（您是否克隆了最新的主版本？）。当我使用最新的主分支转换检测训练集时，我无法在本地重现您的错误。
> 
> 我正在转换从[https://bdd-data.berkeley.edu/portal.html#download](url)下载的 10k 图像旁边的标签[](url)
> 
> 在 google colab 上使用最新版本的 master。
> 
> 我的代码
> 
> `!git clone https://github.com/bdd100k/bdd100k` `!pip install -r requirements.txt ` `!python3 setup.py install` `!pip install -U nanoid numpy pydantic boto3` `python3 -m bdd100k.label.to_coco -m det -i bdd100k_labels_images_val.json -o val2.json `
> 
> 非常感谢！！！！
> 
> 编辑：原来我使用了错误版本的标签文件。该程序使用 2020 检测标签运行良好。

hello,

> > Could you give us more information on which data (bdd100k detection train?) you're trying to convert and which version of the code you're using (did you clone the latest master?). I can't reproduce your error locally when i convert the detection train set using the latest master branch.
> 
> I'm converting the labels right next to 10k image downloaded from [https://bdd-data.berkeley.edu/portal.html#download](url)
> 
> using the latest version of master on google colab.
> 
> My code
> 
> `!git clone https://github.com/bdd100k/bdd100k` `!pip install -r requirements.txt ` `!python3 setup.py install` `!pip install -U nanoid numpy pydantic boto3` `python3 -m bdd100k.label.to_coco -m det -i bdd100k_labels_images_val.json -o val2.json `
> 
> Thank you so much!!!!
> 
> edit: Turns out I used the wrong version of label file. The program works fine using 2020 detection label.

Excuse me, I have  the same problem, and i download the data from  https://bdd-data.berkeley.edu/portal.html#download. 
can you tell me , How did you solve it， thinks!

**Comment by liuliaocheng** [comment]
> > Could you give us more information on which data (bdd100k detection train?) you're trying to convert and which version of the code you're using (did you clone the latest master?). I can't reproduce your error locally when i convert the detection train set using the latest master branch.
> 
> I'm converting the labels right next to 10k image downloaded from [https://bdd-data.berkeley.edu/portal.html#download](url)
> 
> using the latest version of master on google colab.
> 
> My code
> 
> `!git clone https://github.com/bdd100k/bdd100k` `!pip install -r requirements.txt ` `!python3 setup.py install` `!pip install -U nanoid numpy pydantic boto3` `python3 -m bdd100k.label.to_coco -m det -i bdd100k_labels_images_val.json -o val2.json `
> 
> Thank you so much!!!!
> 
> edit: Turns out I used the wrong version of label file. The program works fine using 2020 detection label.

Excuse me, I have the same problem, and i download the data from https://bdd-data.berkeley.edu/portal.html#download.
can you tell me , How did you solve it， thinks!

**Comment by wuyunnben** [comment]
+1
