### ISSUE TITLE
Split the image data in to night and day 

### ISSUE THREAD

**Issue by oliver0922** [bdd100k/bdd100k#192]
Hi thanks for your good repository

Is there any way to split the datasets in to night time and day?

I want to use the datasets for training the Cycle GAN

**Comment by tobiasfshr** [comment]
Hi, you can find the image tags in the detection 20 labels. Each frame will have attributes like this:
`{'weather': 'clear', 'timeofday': 'daytime', 'scene': 'city street'}`
