### ISSUE TITLE
KeyError: 'labels' when running to_coco.py conversion

### ISSUE THREAD

**Issue by onepoint16** [bdd100k/bdd100k#209]
Hi @fyu I saw that you had previously delt with a similar issue. I seem to be getting a if frame["labels"]: KeyError: 'labels' when running the `python -m bdd100k.label.to_coco -m det     -i /home/sam/Desktop/labels-original/det_20/det_train.json     -o /home/sam/Desktop/labels/det_20/det_train_cocofmt.json
`
I have looked within the to_coco.py file but can't figure why this won't run. Any advice would be great

**Comment by onepoint16** [comment]
I managed to solve my issue. I changed line 145 in to_coco.py from  if frame["labels"] to if frame.get("labels", None) and the detection label conversion worked. 

For the box track I had to change some of the key names in to_coco.py to match the dataset labels.

**Comment by thomasehuang** [comment]
See #152.
