### ISSUE TITLE
'name' incosistency in seg_track_20 JSONs for MOTS labels

### ISSUE THREAD

**Issue by jihun-yoon** [bdd100k/bdd100k#216]
Hello, I found some name inconsistency in JSON files which make errors while converting format using to_coco.py script.

Most of the 'name' values in the JSON files consist of `'videoName-framenubmer.jpg'`.
However, the name of the following files is like `videoName/videoName-framenubmer.jpg`.

A list of files:
0062e803-38c0a33a.json
000f157f-dab3a407.json
006fdb67-f4820206.json
0062f18d-f8cd3a65.json

**Comment by thomasehuang** [comment]
Should be fixed, you can try redownloading the annotations and trying
