### ISSUE TITLE
There are no weather or location conditions for the 10K dataset.

### ISSUE THREAD

**Issue by Genie-Kim** [bdd100k/bdd100k#22]
There are no weather or location conditions for 10K datasets.

Thanks for making a good library.

By the way, about 4000 sheets of semantic segmentation dataset (10K) are not in 100K json label files.
Therefore, it is not possible to know the weather or location condition of some images in the segmentation dataset (10K).

The current segmentation dataset (10K) of BDD100K is just a segmentation dataset. There is no information about various conditions such as weather.
Is there any way to infer the weather or location condition of the segmentation dataset (10K)?

Or can I get an instance segmenation label for 100K??

**Comment by theo2021** [comment]
Metadata for the semantic segmentation (e.g weather and time of the day) would be also extremely important for my research. Are there plans on releasing them?

**Comment by hutec** [comment]
See the answer [here](https://github.com/bdd100k/bdd100k/discussions/38)

> we are revising the labels on our instance segmentation dataset.

Meanwhile a subset of the 10K dataset is already contained in the 100K label file.

**Comment by sonalrpatel** [comment]
It would be useful to have the Metadata information about all 10k segmentation dataset. Is there any plan by when will it be available?

**Comment by thomasehuang** [comment]
We will release updated tagging annotations including those on the 10K segmentation set.
