### ISSUE TITLE
the dataset of CVPR2022 Competition

### ISSUE THREAD

**Issue by yu-Mas** [bdd100k/bdd100k#226]
Are the corresponding datasets of CVPR2022 Competition MOTS and MOT respectively MOTS2020Images and MOT2020Images?
Thanks

**Comment by fyu** [comment]
Yes

**Comment by yu-Mas** [comment]
您好，邮件已收到，我会尽快处理，谢谢。

**Comment by yu-Mas** [comment]
您好，邮件已收到，我会尽快处理，谢谢。
