### ISSUE TITLE
Cannot download MOT2020 Labels

### ISSUE THREAD

**Issue by fafa114** [bdd100k/bdd100k#230]
First,Thanks for your work!
 I cannot download MOT 2020 labels from https://bdd-data.berkeley.edu/portal.html#download.  But I successfully get the all MOT2020 images,I don't know why.

**Comment by siyliepfl** [comment]
Please describe your errors so that we can know what's happening.

**Comment by fafa114** [comment]
Thank you for your timely reply . When I click 'MOT 2020 Labels', it shows “This XML file does not appear to have any style information associated with it. The document tree is shown below.”  I don't know what happened.

**Comment by fafa114** [comment]
Thank you. This problem has been solved. I use the command ："wget https://bdd-data-storage-release.s3.us-west-2.amazonaws.com/bdd100k/2021/bdd100k_box_track_20_labels_trainval.zip" . The labels has been downloaded successfully.
