### ISSUE TITLE
How do I convert the BDD100K dataset to something like YoutubeVIS or video instance split dataset

### ISSUE THREAD

**Issue by Alxx999** [bdd100k/bdd100k#238]

**Comment by siyliepfl** [comment]
Youtube VIS follows the coco format. BDD100k is in the [scalabel format](https://doc.scalabel.ai/format.html). You can find the conversion scripts in the [scalabel repo](https://github.com/scalabel/scalabel/blob/master/scalabel/label/to_coco.py).  You can refer to this script as an example of how to do the conversion. Maybe you need to adjust some key values to make them consistent with the YoutubeVIS definition.

**Comment by Alxx999** [comment]
> Youtube VIS follows the coco format. BDD100k is in the [scalabel format](https://doc.scalabel.ai/format.html). You can find the conversion scripts in the [scalabel repo](https://github.com/scalabel/scalabel/blob/master/scalabel/label/to_coco.py). You can refer to this script as an example of how to do the conversion. Maybe you need to adjust some key values to make them consistent with the YoutubeVIS definition.

OK! Thank you!
