### ISSUE TITLE
End-to-end annotations in BDD100k?

### ISSUE THREAD

**Issue by neel04** [bdd100k/bdd100k#245]
### Discussed in https://github.com/bdd100k/bdd100k/discussions/243

<div type='discussions-op-text'>

<sup>Originally posted by **neel04** May 25, 2022</sup>
Hi, thanks for such a wonderfully comprehensive dataset! 🤗 

I had a quick question - Does BDD100K have steering/direct trajectory annotations? Apparently, according to the [DBNet](http://www.dbehavior.net/data/egpaper_release.pdf) paper there is indeed; However, the documentation only mentions GPS trajectories and IMU data 🤔

So is there any such data to train models end-to-end with this dataset (for *imitation learning*), like the Comma.ai dataset (which has direct steering angles)?

**EDIT:** This is specifically regarding the annotations for the larger set of 100k video clips</div>

**Comment by neel04** [comment]
Sorry to annoy you @siyliepfl @tobiasfshr but I would really love some guidance/advice regarding this. I'm sure other people would have similar queries regarding imitation learning at some point, and this issue can become a go-to point as a FAQ 🤗

**Comment by fyu** [comment]
@neel04 You can check this [paper](https://www.vis.xyz/pub/end-to-end-learning-of-driving-models/) and its [code](https://github.com/gy20073/BDD_Driving_Model) for using BDD100K labels to learn driving models. They use a different dataset, but the data format is the same.

**Comment by neel04** [comment]
Thank you so much for helping me out! ❤️ you really made my day 🚀 
The repo is a little old, with some ancient dependencies (TF `0.11` 😅) but I'll figure it out. 
Many thanx again!
