### ISSUE TITLE
eval.ai is not working

### ISSUE THREAD

**Issue by zyayoung** [bdd100k/bdd100k#247]
My submission to eval.ai has been in the status of SUBMITTED for about one day without any feedback. Execution time is N/A and result/stdout/stderr are all None.

My submission was to BDD100K Multiple Object Tracking / Testing Phase.
We follow instructions on [BDD100K->Evaluation->Multiple Object Tracking](https://doc.bdd100k.com/evaluate.html#multiple-object-tracking) and use the following zip command to create "a zip file of a folder that contains JSON files of each video."
```
zip test_bdd.zip data/c*
```

Could you please kindly help us to figure out whether it is a submission format or an eval server issue?

**Comment by siyliepfl** [comment]
are you submitting to our cvpr challenge server? Could you please tell us your challenge ID?

**Comment by zyayoung** [comment]
> are you submitting to our cvpr challenge server? Could you please tell us your challenge ID?

Yes. the challenge ID is [1259](https://eval.ai/challenge/1259/). My eval.ai user name is zyayoung.

**Comment by siyliepfl** [comment]
The 1259 challenge is currently under upgrading of eval ai's new evaluation server. If you need the results urgently, you can participate and try our MOT CVPR challenge server : )

**Comment by AliNaqvi110** [comment]
Hi I also facing similar kind of problem

I have trained a model on bdd100k images datasets. 
Generated test label json file using scalable format.

How can I evaluate model.
Can you provide me test data ground truth.
Eval server is not responding.

Any help will be appreciated.
Many thanks
