### ISSUE TITLE
BDD100K Object Detection on EvalAI submission FileNotFoundError

### ISSUE THREAD

**Issue by Chung-Lucy** [bdd100k/bdd100k#289]
I submitted my testing result of BDD100K Object Detection Challenge on EvalAI, and get the status of testing is "Failed" with the following error message:

Traceback (most recent call last):
File "/code/scripts/workers/submission_worker.py", line 508, in run_submission
submission_metadata=submission_serializer.data,
File "/tmp/tmpebqg16sx/compute/challenge_data/challenge_1857/main.py", line 76, in evaluate
results = load(user_submission_file, nprocs=1).frames
File "/usr/local/lib/python3.7/site-packages/scalabel/label/io.py", line 81, in load
raise FileNotFoundError(f"{inputs} does not exist.")
FileNotFoundError: /tmp/tmpebqg16sx/compute/submission_files/submission_242106/b0ca67e6-1b64-4bd8-a0d1-c774eb179ad5.json does not exist.

Please help me to resolve the problem and get the testing result, thanks!

**Comment by Chung-Lucy** [comment]
Thanks for replying my issue. After the submission is failed, I have submitted my result again on December 30, 2022. Now, the status is stiled "Runnung". Besides, if I submit other result, the website is not working. After I refresh the websit, there isn't any new result on "My Submissions". Please help me resolve the problems. Thank you very much!

**Comment by Chung-Lucy** [comment]
> > > The eval ai platform might delete your submission. Could you try to submit it again? Please let us know if the resubmission doesn't work.
> > 
> > 
> > Thanks for replying my issue. After the submission is failed, I have submitted my result again on December 30, 2022. Now, the status is stiled "Runnung". Besides, if I submit other result, the website is not working. After I refresh the websit, there isn't any new result on "My Submissions". Please help me resolve the problems. Thank you very much!
> 
> We will check this for you. What is your submission id?

My submission id is 242574.

**Comment by Chung-Lucy** [comment]
@siyliepfl Thank you very much for your help! I have got my result.

**Comment by siyliepfl** [comment]
You're welcome. I will close this issue.
