### ISSUE TITLE
EvalAI status stuck on "Runnung"

### ISSUE THREAD

**Issue by a0962** [bdd100k/bdd100k#293]
I have subutted my test result on BDD100K Object Detection Challenge at Jan 7, 2023 5:20:46 PM, but the status is still "Running". Is it Normal?

**Comment by siyliepfl** [comment]
No, it is not normal. We will check this for you. What's your submission id?

**Comment by a0962** [comment]
> No, it is not normal. We will check this for you. What's your submission id?

OK, I got it. My submission id is 243629. Thanks for your checking!

**Comment by siyliepfl** [comment]
It should work. Please check again for your result. I will close this issue
