### ISSUE TITLE
Not able to find instance segmentation data.

### ISSUE THREAD

**Issue by souravagarwal** [bdd100k/bdd100k#3]
Hi, I was trying to download the instance segmentation data, but all i see is semantic segmentation without differentiation among individual instances. Also, in the detection20 data, all poly2d fields are None. Please let me know if I am missing some other dataset.

Thanks!

**Comment by Jacobew** [comment]
Hi, same problem here. Did you find the instance segmentation annotations of BDD? @souravagarwal

**Comment by griffintin** [comment]
I thought the instance and semantics info. maybe encoded to 1 image under seg/ folder. After read the image, flattened_ids= [  0   2   3   5   6   7   8  10  13  14  15 255]. what does the number means? Is there any format description about the segmentation?

**Comment by griffintin** [comment]
@fyu   
When will instance segmentation label be released?  I heard it will be in April, what about the schedule?

**Comment by XiaLiPKU** [comment]
Hi all!
Thanks for your attention to BDD100K. Now you can find labels of instance segmentation on: https://www.bdd100k.com/.
We've also released the test server at: https://competitions.codalab.org/competitions/30769

**Comment by sparshgarg23** [comment]
Hi,i know its been a long time so not sure if the repo is being maintained or not but the link for downloading instance seg labels is down could you provide new link. thanks
