### ISSUE TITLE
MOT2020 source offline; downloads dead slow when it was online

### ISSUE THREAD

**Issue by evdcush** [bdd100k/bdd100k#300]
The MOT2020 images/labels source is offline currently:
http://dl.yf.io/bdd100k/mot20/

![screencap_2023-02-22_19-54-50](https://user-images.githubusercontent.com/28853935/220600124-55a47a00-b04e-4a22-ad52-0a6567b53105.png)

Also, when it was online (~2 days prior), the download speeds were so slow as to be functionally identical to being offline.
I was getting download speeds averaging around ~`30kb/s`.

Is there any mirror or torrent for acquiring this data?
(Any users with this data able to share with me a Drive link or something with verifiable MD5?)

**Comment by fyu** [comment]
Thanks for reporting. We are aware of the issue and the IT staff is working on restoring the download. We are humbled to receive so many downloading requests and traffic for our dataset, which overwhelmed the infrastructure. 

The IT staff has already started working on setting up torrent for better data distribution. We are also exploring effective ways to mirror the data in the long term. However, Google Drive or others don't work for us because web drives limit the number of downloads in a period. We are now above that limit.

**Comment by evdcush** [comment]
@fyu 
Thank you for your prompt response and message!
While it's constraining not being able to get the data, I am glad to hear there has been so much demand.

It would be great to see a torrent for these files!

As for other potential distribution/hosting solutions, for your and the BDD100K team's consideration, it may be possible to share the data with GitHub releases.

You could chunk files into 2GB binaries, [the limit for individual file sizes in a release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas), add each chunk as a file in a release, and users can download the whole release.

I have not seen this done before, but sharing large binaries (> 1GB) through GH releases was common in the tensorflow community for sharing custom-built TF wheels, and the [official GH docs](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas) specifically say:

> Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

![screencap_2023-02-23_23-00-15](https://user-images.githubusercontent.com/28853935/220929173-d44a1052-b505-44ac-b2b4-ee486ace157d.png)

If I am successful in downloading at *least* `bdd100k/mot20/images20-track-val-1.zip`, I might push the data to a release in a personal repo for others'.

At any rate, I will close this comment, as the source is back online (though still slow). Thank you for your reply.

---

(Regarding the Google Drive comment, that was wrt end-users who had already acquired the MOT subsets and was willing to share, rather than as a solution for BDD100K hosting)
