### ISSUE TITLE
Multiprocessing Error

### ISSUE THREAD

**Issue by pranav-ap** [bdd100k/bdd100k#315]
Hey,

I ran the command `python -m bdd100k.label.to_coco -m det -i <path> -o <path>`, and got the following error related to multithreading. How can we fix this?

1. Install scalabel using pip
2. Run above command
3. See error

![image](https://github.com/bdd100k/bdd100k/assets/11399494/b74ff4c7-97ea-4da4-a299-4e6b23d14edc)

![image](https://github.com/bdd100k/bdd100k/assets/11399494/83e47a77-adab-49d8-a5a0-0ac7c96fe1b8)

 - OS: Windows 11

**Comment by cui19981127** [comment]
hello，I have the same problem. How did you solve it？Thanks

**Comment by LiuXuan66** [comment]
hello，I have the same problem. How did you solve it？Thanks

**Comment by LiuXuan66** [comment]
> 

hello，I have the same problem. How did you solve it？Thanks

**Comment by SiBensberg** [comment]
The scalabel code seems to be incompatible with the new pydantic 2.0 release. Downgrading to  `pydantic` 1.10.12 fixed it for me.
```pip install pydantic==1.10.12```
