### ISSUE TITLE
EvalAI submission issue, urgent!

### ISSUE THREAD

**Issue by Tharrengini** [bdd100k/bdd100k#333]
I submitted a zip file of a folder containing test masks as suggested under semantic segmentation evaluation documentation (https://doc.bdd100k.com/evaluate.html#semantic-segmentation), for the Bdd100k semantic segmentation challenge. The status has been "SUBMITTED" for sometime now and I am yet to receive a response. Do I need to submit a .json file or is the server not responding for this challenge at the moment?

**Comment by Carmanlst** [comment]
Sorry to bother you,Hello, now the data set website is not accessible, may I ask you to ask for a data set?
