### ISSUE TITLE
KeyError: 'category'

### ISSUE THREAD

**Issue by Pari-singh** [bdd100k/bdd100k#4]
Hi, I am trying to run the evaluation script for detection alone, to evaluate my model output. But I am getting the following error:

File "bdd100k/bdd100k/eval/evaluate.py", line 133, in group_by_key
    groups[d[key]].append(d)
KeyError: 'category'

**Comment by XiaLiPKU** [comment]
Thanks for informing!
Now we've updated all evaluation scripts. You can try new versions.
