### ISSUE TITLE
Imu data from dataset

### ISSUE THREAD

**Issue by visanz2** [bdd100k/bdd100k#5]
Hi,

I can see that the images from bdd100k are the keyframes of the videos taken every 10 seconds. I would like to know if it is possible to get the car speed. I saw that the "info" download information contains the IMU and GPS data (The GPS/IMU information recorded along with the videos). Is it possible to get that information as well per image? The json file of the video and the image json file has the same name, however the "info" json file has several images (each frame on the video), which image in the bdd100k corresponds to the "info" json file and the image json file always has 10000 of timestamp. Is any way to obtain this information from the dataset?

Thanks

**Comment by fyu** [comment]
Please ask the dataset questions in our forum: https://groups.google.com/g/bdd100k-discuss
