### ISSUE TITLE
Many object labels are wrong 

### ISSUE THREAD

**Issue by sainisanjay** [bdd100k/bdd100k#51]
After visualisation it been observed that many objects labels has wrong values like Truck is annotated as Car and Most of time (Van) is sometime annotated as Car and sometime Truck.
Is it due to manual or human errors? 
Few examples:
![10](https://user-images.githubusercontent.com/25616511/112095124-ec0a9e80-8bc1-11eb-8568-066374822c56.jpg)
![21](https://user-images.githubusercontent.com/25616511/112097501-22e2b380-8bc6-11eb-8e8e-96323e0c899e.jpg)
![2](https://user-images.githubusercontent.com/25616511/112095138-f0cf5280-8bc1-11eb-80a8-ef6eab6e3310.jpg)

Further, such object annotated which human eyes also can't recognised   
![1](https://user-images.githubusercontent.com/25616511/112097114-77d1fa00-8bc5-11eb-8db7-50243ba9fd16.jpg)
![20](https://user-images.githubusercontent.com/25616511/112097513-29712b00-8bc6-11eb-943b-61a02b2db31a.jpg)

1st image Truck is annotated as Car
2nd image again Truck is annotated as Car
3rd image Car (Van is European country) is annotated as Truck, however most of images such object is annotated as Car.
4th & 5th image such objects are annotated that can't be recognised by human eyes.

Does BDD trying to correct or improved wrongly annotated objects?

**Comment by griffintin** [comment]
Similar situation happened when I try to visualize, lables are indeed wrongly attached in the provided labeling data.

@fyu are you going to check this and update ?

**Comment by fyu** [comment]
Are you referring to `Detection 2020 Labels` here?

**Comment by sainisanjay** [comment]
@fyu Yes, i am referring `Detection 2020 Labels` (`det_v2_train_release.json` and `det_v2_val_release.json`)

**Comment by fyu** [comment]
OK. Thanks for letting us know. We will look into them. Those are human annotation errors, which are unavoidable when we have so many images to label. But overall, after our multiple rounds of quality check, the labels should be in a stable state.

**Comment by utkutpcgl** [comment]
Thanks for your great contribution!

Is there an update on this issue or a corrected version of `Detection 2020 Labels`? I also noticed serious labeling issues (regarding rider, motorcycle, and bicycle classes).
