### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by haozy008** [bdd100k/bdd100k#6]
When I run the code bdd100k2coco.py I got an error as follow:
 "File "bdd100k2coco.py", line 130, in bdd100k2coco_det
    image["file_name"] = frame['name']
TypeError: list indices must be integers or slices, not str"

Does any one know why?
thanks

**Comment by xinw1012** [comment]
Hi, 

thanks for your interest in our work.  Could you provide more details about the command you were using as well as the annotation labels?

When you download the latest BDD100K detection set from the website, you will see the labels in the BDD100K format named `det_v2_{train,val,test}_release.json`.  To convert it, you can run `python3 bdd100k/label/bdd100k2coco.py -i /path/det_v2_val_releast.json -o /path/det_v2_val_coco.json`.  For the training set,  if you want to remove the additional classes (e.g., other person, other vehicle) in the annotations, you can add the flag `--remove-ignore` in the command. 

Let us know if there is still an issue for you.

**Comment by haozy008** [comment]
Thanks very much! 
My issue is solved

**Comment by sainisanjay** [comment]
@xinw1012 I am facing some issue during bdd to coco conversion. 
I am running below command:
```
python bdd100k/label/to_coco.py -i /home/adas/workspace/data/BDD/bdd100k_labels_detection20/bdd100k/labels/detection20/det_v2_val_release.json -o /home/adas/workspace/data/BDD/bdd100k_labels_detection20/bdd100k/labels/detection20/det_v2_val_coco.json
Traceback (most recent call last):
  File "bdd100k/label/to_coco.py", line 27, in <module>
    from ..common.logger import logger
ValueError: attempted relative import beyond top-level package
```
Configuration: 
Ubuntu 18.04.5 LTS
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux

**Comment by sainisanjay** [comment]
@xinw1012 I was able to convert into bdd to coco. Could you help me, how we can convert into coco to Pascal VOC?
