### ISSUE TITLE
MOTS20 download link 403

### ISSUE THREAD

**Issue by Sebastian-Vogt** [bdd100k/bdd100k#75]
Hi,

I am trying to download the MOTS20 images via this link: http://dl.yf.io/bdd100k/mots20/bdd100k_seg_track_20_images.zip
and get a "403 Forbidden" error.
I can download the version in the tmp folder, but at least there labels and images do not fit together.

Just one example:
This training image (seg_track\train\002b485a-3f6603f2\002b485a-3f6603f2-0000180.jpg)
![002b485a-3f6603f2-0000180](https://user-images.githubusercontent.com/12019404/115670311-93a5f880-a349-11eb-97bf-07895679b3a1.jpg)

should belong to this colormap label (seg_track_20\colormaps\train\002b485a-3f6603f2\002b485a-3f6603f2-0000180.png)
![002b485a-3f6603f2-0000180](https://user-images.githubusercontent.com/12019404/115670117-593c5b80-a349-11eb-89ca-0dfaf9b43436.png)

and this bitmask
![002b485a-3f6603f2-0000180](https://user-images.githubusercontent.com/12019404/115670437-b33d2100-a349-11eb-8a8a-029668f845ac.png)

Is this a problem with the tmp version?
And how do i get access to the real one?

**Comment by fyu** [comment]
Thank you for letting us know. The download access is fixed now.

**Comment by XiaLiPKU** [comment]
Thanks for informing us. Yep, the error occurs in the previous version of releasing. We've updated the links, please use the latest version.

**Comment by Sebastian-Vogt** [comment]
Thanks. The download is fixed as @fyu said and at the first look, the labels correspond to the images.
