### ISSUE TITLE
Missing id field in prediction results

### ISSUE THREAD

**Issue by guarin** [bdd100k/bdd100k#85]
Hi, I followed https://doc.bdd100k.com/evaluate.html#detection to save my prediction results in the correct format but I get the following error when running bdd100k.eval.run:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/env/lib/python3.7/site-packages/scalabel/common/parallel.py", line 30, in run
    q_out.put((i, func(x[0])))
  File "/home/env/lib/python3.7/site-packages/scalabel/label/io.py", line 18, in parse
    return Frame(**humps.decamelize(raw_frame))
  File "/home/env/lib/python3.7/site-packages/scalabel/label/typing.py", line 96, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 100 validation errors for Frame
labels -> 0 -> id
  field required (type=value_error.missing)
labels -> 1 -> id
  field required (type=value_error.missing)
labels -> 2 -> id
  field required (type=value_error.missing)
labels -> 3 -> id
  field required (type=value_error.missing)
labels -> 4 -> id
  field required (type=value_error.missing)
labels -> 5 -> id
```

The issue seems that each label should also have an id. What should this id be set to?

**Comment by XiaLiPKU** [comment]
> Hi, I followed https://doc.bdd100k.com/evaluate.html#detection to save my prediction results in the correct format but I get the following error when running bdd100k.eval.run:
> 
> ```
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/env/lib/python3.7/site-packages/scalabel/common/parallel.py", line 30, in run
>     q_out.put((i, func(x[0])))
>   File "/home/env/lib/python3.7/site-packages/scalabel/label/io.py", line 18, in parse
>     return Frame(**humps.decamelize(raw_frame))
>   File "/home/env/lib/python3.7/site-packages/scalabel/label/typing.py", line 96, in __init__
>     super().__init__(**data)
>   File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 100 validation errors for Frame
> labels -> 0 -> id
>   field required (type=value_error.missing)
> labels -> 1 -> id
>   field required (type=value_error.missing)
> labels -> 2 -> id
>   field required (type=value_error.missing)
> labels -> 3 -> id
>   field required (type=value_error.missing)
> labels -> 4 -> id
>   field required (type=value_error.missing)
> labels -> 5 -> id
> ```
> 
> The issue seems that each label should also have an id. What should this id be set to?

Thanks for your informing. That's really a bug.
We updated our documents yesterday, and you can find them here: https://doc.bdd100k.com/evaluate.html#submission-format
For the. detection task, you can safely generate random str for the 'id' field.
It is only used for JSON loading and parsing, and will not influence the evaluation process
