### ISSUE TITLE
Evaluation on subset

### ISSUE THREAD

**Issue by guarin** [bdd100k/bdd100k#90]
Hi, I generated detection results for a subset of the categories in BDD100K and I would like to get the evaluation scores. 

Just running the default evaluation code does not work as it generates a default value of -1 for all scores of all missing categories:
```
Evaluate category: traffic sign
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.37s).
Accumulating evaluation results...
DONE (t=0.01s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
...
```

The -1 scores are included in the final mAP calculation which is therefore completely wrong.

I also tried removing the categories in question (traffic light and traffic sign) from the config file but this results in an error from scalabel as it assumes that at least one `cat_extensions` is set in the config:
```
 File "/home/user/env/lib/python3.7/site-packages/scalabel/label/to_coco.py", line 551, in load_coco_config
    categories, cat_extensions = cfgs["categories"], cfgs["cat_extensions"]
KeyError: 'cat_extensions'
```

How could I achieve this?

**Comment by XiaLiPKU** [comment]
The mAP is computed without considering those missing categories, you can find the line here: https://github.com/bdd100k/bdd100k/blob/31697688cca545e89db3684eed52a88cb67e00fa/bdd100k/eval/detect.py#L179.

For the latter issue, I will try to solve it later.
Thanks for your informing!

**Comment by guarin** [comment]
Thanks a lot!
